name: Badge

on:
  - push
  - pull_request

jobs:
  badge_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dynamic Badges
        uses: Schneegans/dynamic-badges-action@v1.4.0
        with:
          auth: ${{ secrets.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 }}
          gistID: c00a854f1d43e9f347339b3f39105021
          filename: badge.json
          label: version
          message: 1.0
          color: blue